const CART_ACTION_TYPES = {
    SET_CART: 'SET_CART',
    ADD_TO_CART:'ADD_TO_CART',
    REMOVE_FROM_CART:'REMOVE_FROM_CART',
    SET_IS_CART_OPEN:'SET_IS_CART_OPEN'
};

export default CART_ACTION_TYPES;